import jsPDF from "jspdf";
import { DocumentArrowDownIcon } from "@heroicons/react/24/outline";

const ReportGenerator = ({ result }) => {

  const generateReport = async () => {

    if (!result) {
      alert("No analysis result available.");
      return;
    }

    try {

      const pdf = new jsPDF();

      // =====================================
      // TITLE
      // =====================================

      pdf.setFontSize(22);
      pdf.setFont("helvetica", "bold");
      pdf.text("GeoVision AI", 20, 25);


      // =====================================
      // SUBTITLE
      // =====================================

      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");

      pdf.text(
        "AI-Powered Satellite Change Detection Report",
        20,
        35
      );


      // =====================================
      // DIVIDER
      // =====================================

      pdf.line(20, 42, 190, 42);


      // =====================================
      // ANALYSIS SUMMARY
      // =====================================

      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");

      pdf.text(
        "Analysis Summary",
        20,
        55
      );


      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");


      pdf.text(
        `Changed Regions: ${result.changed_regions}`,
        20,
        68
      );


      pdf.text(
        `Changed Area: ${result.changed_area_percentage}%`,
        20,
        78
      );


      const status =
        result.changed_regions > 0
          ? "Change Detected"
          : "No Change";


      pdf.text(
        `Detection Status: ${status}`,
        20,
        88
      );


      pdf.text(
        `AI Confidence: ${result.confidence}%`,
        20,
        98
      );


      // =====================================
      // COMPARISON IMAGE
      // =====================================

      const imageUrl =
        `http://localhost:8000/${result.comparison_image.replace(
          /\\/g,
          "/"
        )}`;


      const response = await fetch(imageUrl, {
        method: "GET",
        mode: "cors",
        credentials: "include",
      });


      if (!response.ok) {
        throw new Error(
          "Could not load comparison image."
        );
      }


      const blob = await response.blob();


      const imageData =
        await new Promise((resolve) => {

          const reader =
            new FileReader();

          reader.onloadend = () => {
            resolve(reader.result);
          };

          reader.readAsDataURL(blob);

        });


      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");

      pdf.text(
        "Comparison Result",
        20,
        115
      );


      pdf.addImage(
        imageData,
        "PNG",
        20,
        125,
        170,
        100
      );


      // =====================================
      // FOOTER
      // =====================================

      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");


      pdf.text(
        "Generated by GeoVision AI",
        20,
        285
      );


      pdf.text(
        new Date().toLocaleString(),
        140,
        285
      );


      // =====================================
      // SAVE
      // =====================================

      pdf.save(
        "GeoVision-AI-Analysis-Report.pdf"
      );

    } catch (error) {

      console.error(
        "PDF generation error:",
        error
      );

      alert(
        "Unable to generate the PDF report. Please try again."
      );

    }
  };


  return (

    <button
      onClick={generateReport}
      className="
        group
        w-full
        mt-4
        flex
        items-center
        justify-center
        gap-3
        rounded-xl
        border
        border-purple-400/40
        bg-purple-500/10
        px-6
        py-4
        text-sm
        font-bold
        uppercase
        tracking-wider
        text-purple-300
        transition-all
        duration-200
        hover:border-purple-300
        hover:bg-purple-500/20
        hover:text-purple-200
        hover:shadow-[0_0_30px_rgba(168,85,247,0.18)]
      "
    >

      <DocumentArrowDownIcon
        className="
          w-6
          h-6
          transition-transform
          duration-200
          group-hover:-translate-y-1
        "
      />

      Download PDF Report

    </button>

  );
};

export default ReportGenerator;