import jsPDF from "jspdf";

const ReportGenerator = ({ result }) => {
  const generateReport = async () => {
    if (!result) {
      alert("No analysis result available.");
      return;
    }

    try {
      const pdf = new jsPDF();

      // Title
      pdf.setFontSize(22);
      pdf.setFont("helvetica", "bold");
      pdf.text("GeoVision AI", 20, 25);

      // Subtitle
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(
        "AI-Powered Satellite Change Detection Report",
        20,
        35
      );

      // Divider
      pdf.line(20, 42, 190, 42);

      // Report information
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Analysis Summary", 20, 55);

      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");

      pdf.text(
        `Changed Regions: ${result.changed_regions}`,
        20,
        68
      );

      pdf.text(
        `Changed Area: ${result.changed_area_percentage}%`,
        20,
        78
      );

      const status =
        result.changed_regions > 0
          ? "Change Detected"
          : "No Change";

      pdf.text(`Detection Status: ${status}`, 20, 88);

      pdf.text("AI Confidence: 98%", 20, 98);

      // Fetch comparison image
      const imageUrl =
        `http://127.0.0.1:8000/${result.comparison_image.replace(
          /\\/g,
          "/"
        )}`;

      const response = await fetch(imageUrl);

      if (!response.ok) {
        throw new Error("Could not load comparison image.");
      }

      const blob = await response.blob();

      const imageData = await new Promise((resolve) => {
        const reader = new FileReader();

        reader.onloadend = () => {
          resolve(reader.result);
        };

        reader.readAsDataURL(blob);
      });

      // Add comparison image
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Comparison Result", 20, 115);

      pdf.addImage(
        imageData,
        "PNG",
        20,
        125,
        170,
        100
      );

      // Footer
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");

      pdf.text(
        "Generated by GeoVision AI",
        20,
        285
      );

      pdf.text(
        new Date().toLocaleString(),
        140,
        285
      );

      // Save PDF
      pdf.save("GeoVision-AI-Analysis-Report.pdf");

    } catch (error) {
      console.error("PDF generation error:", error);

      alert(
        "Unable to generate the PDF report. Please try again."
      );
    }
  };

  return (
    <button
      onClick={generateReport}
      className="w-full bg-purple-500 hover:bg-purple-400 text-white font-bold py-4 rounded-xl transition"
    >
      📄 Download PDF Report
    </button>
  );
};

export default ReportGenerator;